=== tizenorg/platform.framework.web.wrt-commons/tests/ace/test-configuration/CMTest/active/bondixml.dtd
<!ENTITY % Object.ANY ''>
<!ENTITY % Method.ANY ''>
<!ENTITY % Transform.ANY ''>
<!ENTITY % SignatureProperty.ANY ''>
<!ENTITY % KeyInfo.ANY ''>
<!ENTITY % KeyValue.ANY ''> <!-- TODO ECDSA IS NOT HANDLED YET -->
<!ENTITY % PGPData.ANY ''>
<!ENTITY % X509Data.ANY ''>
<!ENTITY % SPKIData.ANY ''>


<!ELEMENT signed-policy (Signature, ( policy-set | policy )* ) >
<!-- Start Core Signature declarations, these should NOT be altered -->

<!ELEMENT Signature (SignedInfo, SignatureValue, KeyInfo?, Object*)  >
<!ATTLIST Signature  
	xmlns	CDATA	#FIXED 'http://www.w3.org/2000/09/xmldsig#'
	Id  	ID	#IMPLIED >

<!ELEMENT SignatureValue (#PCDATA) >
<!ATTLIST SignatureValue  
         Id  ID      #IMPLIED>

<!ELEMENT SignedInfo (CanonicalizationMethod, 
	SignatureMethod,  Reference+)  >
<!ATTLIST SignedInfo  
	Id	 ID 	 #IMPLIED 
>

<!ELEMENT CanonicalizationMethod (#PCDATA %Method.ANY;)* > 
<!ATTLIST CanonicalizationMethod 
	Algorithm CDATA #REQUIRED > 

<!ELEMENT SignatureMethod (#PCDATA|HMACOutputLength %Method.ANY;)* >
<!ATTLIST SignatureMethod 
	Algorithm CDATA #REQUIRED > 

<!ELEMENT Reference (DigestMethod, DigestValue)  >
<!ATTLIST Reference
	Id	ID	#IMPLIED
	URI	CDATA	#IMPLIED
	Type	CDATA	#IMPLIED>


<!ELEMENT XPath (#PCDATA) >

<!ELEMENT DigestMethod (#PCDATA %Method.ANY;)* >
<!ATTLIST DigestMethod  
	Algorithm		CDATA	#REQUIRED >

<!ELEMENT DigestValue  (#PCDATA)  >

<!ELEMENT KeyInfo	(#PCDATA|KeyName|KeyValue|RetrievalMethod|
           X509Data|PGPData|SPKIData|MgmtData %KeyInfo.ANY;)* >
<!ATTLIST KeyInfo
	Id	ID	 #IMPLIED >

<!-- Key Information -->

<!ELEMENT KeyName (#PCDATA) >
<!ELEMENT KeyValue (#PCDATA|DSAKeyValue|RSAKeyValue %KeyValue.ANY;)* >
<!ELEMENT MgmtData (#PCDATA) >

<!ELEMENT RetrievalMethod EMPTY>
<!ATTLIST RetrievalMethod
  URI	CDATA #REQUIRED 
  Type	CDATA #IMPLIED > 

<!-- X.509 Data -->

<!ELEMENT X509Data ((X509IssuerSerial | X509SKI | X509SubjectName |
                    X509Certificate | X509CRL )+ %X509Data.ANY;)>
<!ELEMENT X509IssuerSerial (X509IssuerName, X509SerialNumber) >
<!ELEMENT X509IssuerName (#PCDATA) >
<!ELEMENT X509SubjectName (#PCDATA) >
<!ELEMENT X509SerialNumber (#PCDATA) >
<!ELEMENT X509SKI (#PCDATA) >
<!ELEMENT X509Certificate (#PCDATA) >
<!ELEMENT X509CRL (#PCDATA) >

<!-- PGPData -->

<!ELEMENT PGPData ((PGPKeyID, PGPKeyPacket?) | (PGPKeyPacket) %PGPData.ANY;) >
<!ELEMENT PGPKeyPacket  (#PCDATA)  >
<!ELEMENT PGPKeyID  (#PCDATA)  >

<!-- SPKI Data -->

<!ELEMENT SPKIData (SPKISexp %SPKIData.ANY;)  >
<!ELEMENT SPKISexp  (#PCDATA)  >

<!-- Extensible Content -->

<!ELEMENT Object (#PCDATA|Signature|SignatureProperties|Manifest %Object.ANY;)* >
<!ATTLIST Object  
	Id	ID	#IMPLIED
	MimeType	CDATA	#IMPLIED
	Encoding	CDATA	#IMPLIED >

<!ELEMENT Manifest (Reference+)  >
<!ATTLIST Manifest  
	Id	ID	#IMPLIED >

<!ELEMENT SignatureProperties (SignatureProperty+)  >
<!ATTLIST SignatureProperties  
	Id	ID	 #IMPLIED  >

<!ELEMENT SignatureProperty (#PCDATA %SignatureProperty.ANY;)* >
<!ATTLIST SignatureProperty  
	Target 	CDATA	 #REQUIRED
	Id	ID	 #IMPLIED  >

<!-- Algorithm Parameters -->

<!ELEMENT HMACOutputLength (#PCDATA) >

<!ELEMENT DSAKeyValue ((P, Q)?, G?, Y, J?, (Seed, PgenCounter)?) >
<!ELEMENT P (#PCDATA) >
<!ELEMENT Q (#PCDATA) >
<!ELEMENT G (#PCDATA) >
<!ELEMENT Y (#PCDATA) >
<!ELEMENT J (#PCDATA) >
<!ELEMENT Seed (#PCDATA) >
<!ELEMENT PgenCounter (#PCDATA) >

<!ELEMENT RSAKeyValue (Modulus, Exponent) > 
<!ELEMENT Modulus (#PCDATA) >
<!ELEMENT Exponent (#PCDATA) >








<!ELEMENT policy-set (target?, assert*, (policy-set | policy)*) >
<!ATTLIST policy-set
    combine (deny-overrides|permit-overrides|first-matching-target) "deny-overrides"
   id	 ID	 #IMPLIED 
>

<!ELEMENT policy (target?, assert*, rule*) >
<!ATTLIST policy 
    combine (deny-overrides|permit-overrides|first-applicable) "deny-overrides"
    description CDATA #IMPLIED
    id	  ID	 #IMPLIED 
>

<!ELEMENT assert (condition?, set*) >

<!ELEMENT set EMPTY >
<!ATTLIST set attr CDATA #REQUIRED >
<!ATTLIST set value CDATA #REQUIRED >

<!ELEMENT rule (condition?) >
<!ATTLIST rule
    effect (permit|prompt-blanket|prompt-session|prompt-oneshot|deny) "permit"
>

<!ELEMENT target (subject+) >

<!ELEMENT subject (subject-match+) >

<!ELEMENT condition ((condition | subject-match | resource-match | environment-match)+) >
<!ATTLIST condition
    combine (and|or) "and"
>

<!ENTITY % match-attrs '
    attr CDATA #REQUIRED
    match CDATA #IMPLIED
    func (equal|glob|regexp) "glob"
'>

<!ELEMENT subject-match (#PCDATA)>
<!ATTLIST subject-match %match-attrs; >

<!ENTITY % match-model '
    (#PCDATA | subject-attr | resource-attr | environment-attr)*
'>

<!ELEMENT resource-match %match-model;>
<!ATTLIST resource-match %match-attrs;>

<!ELEMENT environment-match %match-model;>
<!ATTLIST environment-match %match-attrs;>

<!ENTITY % attr-attrs 'attr CDATA #REQUIRED'>

<!ELEMENT subject-attr EMPTY>
<!ATTLIST subject-attr %attr-attrs;>

<!ELEMENT resource-attr EMPTY>
<!ATTLIST resource-attr %attr-attrs;>

<!ELEMENT environment-attr EMPTY>
<!ATTLIST environment-attr %attr-attrs;>

=== tizenorg/platform.framework.web.wrt-commons/tests/ace/test-configuration/CMTest/pms_general-test.xml
<!DOCTYPE signed-policy SYSTEM "bondixml.dtd">

<signed-policy>

 <Signature Id="SignatureExample" xmlns="http://www.w3.org/2000/09/xmldsig#"> 
   <SignedInfo> 
   <CanonicalizationMethod Algorithm="http://www.w2.org/2006/12/xml-c14n11"/> 
   <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/> 
   <Reference URI="Policy-1"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-2"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-3"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-4"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-5"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-6"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-7"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-8"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-9"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-10"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-11"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-12"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-13"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-14"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-15"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-16"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
   <Reference URI="Policy-17"> 
     <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/> 
     <DigestValue>dGhpcyBpcyBub3QgYSBzaWduYXR1cmUK...</DigestValue> 
   </Reference> 
 </SignedInfo> 
   <SignatureValue>asdfkjlhxvczxnbcvnjahfjhsdfklahfdas</SignatureValue> 
   <KeyInfo> 
     <KeyValue>
       <DSAKeyValue> 
         <P> PValue </P><Q> QValue </Q><G> Gvalue </G><Y> laj?</Y>
       </DSAKeyValue>
       <RSAKeyValue>
           <Modulus>
               modulus
           </Modulus>
           <Exponent>
               exponent
           </Exponent>
       </RSAKeyValue>
     </KeyValue>
     <X509Data>
         <X509SubjectName> Subject name </X509SubjectName>
         <X509SKI> SKI </X509SKI>
     </X509Data>
   </KeyInfo> 
 </Signature>
 


<policy-set id="Policy-1">      
<policy-set combine="first-matching-target">
    <target>
        <subject>
            <subject-match attr="id">
                subject
            </subject-match>
        </subject>
        <subject>
            <subject-match attr="id" match="subject2" />
        </subject>
    </target>
    <policy>
        <target>
            <subject>
                <subject-match attr="id" match="subject" />
            </subject>
        </target>
        <rule effect="permit">
            <condition>
                <resource-match attr="resource-id">
                    resource
                </resource-match>
                <subject-match attr="version" match="3" />
            </condition>
        </rule>
    </policy>        
    <policy>
        <target>
            <subject>
                <subject-match attr="id" match="subject2" />
            </subject>
        </target>
        <rule effect="deny">
            <condition>
                <resource-match attr="resource-id">
                    resource
                </resource-match>                    
            </condition>
        </rule>
    </policy>    
</policy-set>
<policy-set >
    <target>
        <subject>
            <subject-match attr="id">
                subject3
            </subject-match>                    
        </subject>  
        <subject>
            <subject-match attr="id" match="subject4" />
        </subject>                 
    </target>
    <policy>             
        <rule effect="permit">
            <condition>
                <resource-match attr="resource-id">
                    resource2
                </resource-match>                
            </condition>
        </rule>
    </policy>        
    <policy>            
        <rule effect="deny">
            <condition>
                <resource-match attr="resource-id">
                    resource2
                </resource-match>                    
            </condition>
        </rule>
    </policy> 
    <policy>
        <target>
            <subject>
                <subject-match attr="id">
                    subject4
                </subject-match>                    
                <subject-match attr="version" match="4" />
            </subject>  
        </target>
        <rule effect="permit">
            <condition>
                <resource-match attr="resource-id">
                    resource4
                </resource-match>                    
            </condition>
        </rule>
    </policy>
</policy-set>    
<policy-set id="Policy-2" combine="first-matching-target">
    <target>      
        <subject>
            <subject-match attr="id" match="subject5" />
        </subject>                 
        <subject>
            <subject-match attr="id" match="subject6" />
        </subject>                 
    </target>
    <policy>    
        <target>
            <subject>
                <subject-match attr="id">
                    subject5
                </subject-match>                    
            </subject>              
        </target>
        <rule effect="permit">
            <condition combine="and">
                <resource-match attr="resource-id">
                    resource5
                </resource-match>                
                <subject-match attr="version" match="5" />
            </condition>
        </rule>
    </policy> 
    <policy>             
        <rule effect="permit">
            <condition combine="or">
                <resource-match attr="resource-id">
                    resource6
                </resource-match>                
                <subject-match attr="version" match="6" />
            </condition>
        </rule>
    </policy>  
</policy-set>

<policy-set id="Policy-3" combine="deny-overrides">
    <target>      
        <subject>
            <subject-match attr="id" match="subject7" />
        </subject>                                 
    </target>
    <policy>   
        <rule effect="permit">
            <condition combine="and">
                <resource-match attr="resource-id">
                    resource7
                </resource-match>    
                <condition combine="and">
                    <condition combine="or">
                        <subject-match attr="version" match="7" />
                        <subject-match attr="version" match="6" />
                    </condition>
                    <resource-match attr="author" match="author2" />
                </condition>
            </condition>
        </rule>
    </policy>   
    <policy>   
        <rule effect="permit">
            <condition combine="and">
                <resource-match attr="resource-id">
                    resource7
                </resource-match>    
                <condition combine="or">
                    <condition combine="or">
                        <subject-match attr="version" match="1" />
                        <subject-match attr="version" match="2" />
                    </condition>
                    <resource-match attr="author" match="author3" />
                </condition>
            </condition>
        </rule>
    </policy> 
    <policy>   
        <rule effect="deny">
            <condition combine="and">
                <resource-match attr="resource-id">
                    resource7
                </resource-match>    
                <condition combine="or">
                    <condition combine="or">
                        <subject-match attr="version" match="1" />
                        <subject-match attr="version" match="2" />
                    </condition>
                    <resource-match attr="author" match="author3" />
                </condition>
            </condition>
        </rule>
